// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const USER_MOOD_SUCCESS = 'USER_MOOD_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const CURRENT_USER_PROFILE_SUCCESS = 'CURRENT_USER_PROFILE_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

// People Picker
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const SET_SELECTED_PEOPLE = 'SET_SELECTED_PEOPLE';

// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';


// Dashboard

export const GET_ALL_DASHBOARDS = 'GET_ALL_DASHBOARDS';
export const CREATE_DASHBOARD = 'CREATE_DASHBOARD';
export const UPDATE_DASHBOARD = 'UPDATE_DASHBOARD';
export const GET_DASHBOARD = 'GET_DASHBOARD';
export const SET_EDIT_DASHBOARD = 'SET_EDIT_DASHBOARD';

export const GET_MY_DASHBOARDS = 'GET_MY_DASHBOARDS';
export const GET_SUBSCRIBED_DASHBOARDS = 'GET_SUBSCRIBED_DASHBOARDS';

// user moods
export const SET_DASHBOARD_USERS_FOR_MOOD_SYNC = 'SET_DASHBOARD_USERS_FOR_MOOD_SYNC';
export const GET_DASHBOARD_USERS_FOR_MOOD_SYNC = 'GET_DASHBOARD_USERS_FOR_MOOD_SYNC';


